src/moi_mahiro/beans/Comment.java
package moi_mahiro.beans;

import java.io.Serializable;
import java.util.Date;

public class Comment implements Serializable {
    private static final long serialVersionUID = 1L;

    private int id;
    private int user_id;
    private int message_id;
    private String text;
    private Date created_date;
    private String name;

    public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public void setId(int id) {
    	this.id = id;
    }
    public int getId() {
    	return id;
    }
    public void setMessageId(int message_id) {
    	this.message_id = message_id;
    }
    public int getMessageId() {
    	return message_id;
    }
    public void setUserId(int user_id) {
    	this.user_id = user_id;
    }
    public int getUserId() {
    	return user_id;
    }

    public void setText(String text) {
    	this.text = text;
    }
    public String getText() {
    	return text;
    }
    public void setCreatedDate(Date created_date) {
    	this.created_date = created_date;
    }
    public Date getCreatedDate() {
    	return created_date;
    }
}

src/moi_mahiro/beans/User.java
package moi_mahiro.beans;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    private static final long serialVersionUID = 1L;

    private int id;
    private String login_id;
    private String name;
    private String password;
    private int branch_id;
    private String branch_name;
    private int department_id;
    private String department_name;
    private String is_stopped;
    private Date created_date;
    private Date updated_date;




    public void setName(String name) {
    	this.name = name;
    }
    public String getName() {
    	return name;
    }
    public void setLoginId(String login_id) {
    	this.login_id = login_id;
    }
    public String getLoginId() {
    	return login_id;
    }
    public void setPassword(String password) {
    	this.password = password;
    }
    public String getPassword() {
    	return password;
    }
    public void setBranchId(int branch_id) {
    	this.branch_id = branch_id;
    }
    public int getBranchId() {
    	return branch_id;
    }
    public void setDepartmentId(int department_id) {
    	this.department_id = department_id;
    }
    public int getDepartmentId() {
    	return department_id;
    }
    public void setIsStopped(String is_stopped) {
    	this.is_stopped = is_stopped;
    }
    public String getIsStopped() {
    	return is_stopped;
    }
    public void setCreatedDate(Date createdDate) {
    	this.created_date = createdDate;
    }
    public Date gettCreatedDate() {
    	return created_date;
    }
    public void setUpdatedDate(Date updatedDate) {
    	this.updated_date = updatedDate;
    }
    public Date updatedDate() {
    	return updated_date ;
    }
	public void setId(int id) {
		this.id = id;
	}
	public int getId() {
		return id;
	}
	public void setBranchName(String branchName) {
    	this.branch_name = branchName;
    }
    public String getBranchName() {
    	return branch_name;
    }
    public void setDepartmentName(String departmentName) {
    	this.department_name = departmentName;
    }
    public String getDepartmentName() {
    	return department_name;
	}
	public void setId(Object id) {
		// TODO 自動生成されたメソッド・スタブ

	}
}

src/moi_mahiro/controller/EditServlet.java
package moi_mahiro.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import moi_mahiro.beans.Branches;
import moi_mahiro.beans.Departments;
import moi_mahiro.beans.Management;
import moi_mahiro.beans.User;
import moi_mahiro.service.EditService;
import moi_mahiro.service.LoginService;
import moi_mahiro.service.ManagementService;
import moi_mahiro.service.UserService;

@WebServlet(urlPatterns = { "/edit" })
public class EditServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

    	HttpSession session = request.getSession();
    	List<String> errorMessages = new ArrayList<String>();

        User user = new User();

        if(StringUtils.isBlank(request.getParameter("id"))){
        	errorMessages.add("不正なパラメーターが入力されました");
        	session.setAttribute("errorMessages", errorMessages);

        	response.sendRedirect("./UserManagement");
        	return;
        }
        if(!request.getParameter("id").matches("^[0-9]{1,10}")){
        	errorMessages.add("不正なパラメーターが入力されました");
        	session.setAttribute("errorMessages", errorMessages);

        	response.sendRedirect("./UserManagement");
        	return;
        }
        if(!request.getParameter("id").matches("[+-]?\\d+")){
        	errorMessages.add("不正なパラメーターが入力されました");
        	session.setAttribute("errorMessages", errorMessages);

        	response.sendRedirect("./UserManagement");
        	return;
        }
        user.setId(Integer.parseInt(request.getParameter("id")));

        User users = new EditService().getUser(user);

        if(users.getId() == 0) {
        	errorMessages.add("不正なパラメーターが入力されました");
        	session.setAttribute("errorMessages", errorMessages);

        	response.sendRedirect("./UserManagement");
        	return;
        }
        request.setAttribute("users", users);

        Branches branch = new Branches();
        List<Branches> branches = new UserService().getBranch(branch);
        request.setAttribute("branches", branches);

        Departments department = new Departments();
        List<Departments> departments = new UserService().getDepartment(department);
        request.setAttribute("departments", departments);

        request.getRequestDispatcher("Edit.jsp").forward(request, response);
    }
    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

    	HttpSession session = request.getSession();
    	List<String> errorMessages = new ArrayList<String>();

	    if (isValid(request, errorMessages)) {

	    	User user = new User();
	        user.setId(Integer.parseInt(request.getParameter("id")));
	        user.setName(request.getParameter("name"));
	        user.setLoginId(request.getParameter("loginId"));
	        user.setPassword(request.getParameter("password"));
	        user.setBranchId(Integer.parseInt(request.getParameter("branch_id")));
	        user.setDepartmentId(Integer.parseInt(request.getParameter("department_id")));

	        new EditService().register(user,request);

    		String login_id = request.getParameter("loginUserId");

    		LoginService loginService = new LoginService();
    		User userNew = loginService.loginEdit(login_id);

    		session.setAttribute("loginUser", userNew);

	        response.sendRedirect("./UserManagement");

    	}else {
    		session.setAttribute("errorMessages", errorMessages);
    		User user = new User();
        	user.setId(Integer.parseInt(request.getParameter("id")));
        	user.setName(request.getParameter("name"));
        	user.setLoginId(request.getParameter("loginId"));
        	user.setBranchId(Integer.parseInt(request.getParameter("branch_id")));
        	user.setDepartmentId(Integer.parseInt(request.getParameter("department_id")));


        	new EditService().getUser(user);
        	request.setAttribute("users", user);

        	Branches branch = new Branches();
            List<Branches> branches = new UserService().getBranch(branch);
            request.setAttribute("branches", branches);

            Departments department = new Departments();
            List<Departments> departments = new UserService().getDepartment(department);
            request.setAttribute("departments", departments);

        	request.getRequestDispatcher("Edit.jsp").forward(request, response);
    	}
    }
    private boolean isValid(HttpServletRequest request, List<String> errorMessages) {

    	String password = request.getParameter("password");
	    String checkPass = request.getParameter("checkPassword");
	    String loginId = request.getParameter("loginId");
	    String name = request.getParameter("name");
	    String branchId = request.getParameter("branch_id");
	    String departmentId = request.getParameter("department_id");

	    List<Management> managements = new ManagementService().getManagement();

	    UserService userService = new UserService();
        User user = userService.idCheck(loginId);

        User editUser = new User();
        editUser.setId(Integer.parseInt(request.getParameter("id")));
        editUser.setLoginId(request.getParameter("login_id"));


        if (managements == null) {
    		errorMessages.add("該当ユーザーが存在しません");
        }
        if(!editUser.getLoginId().equals(loginId)) {
        	if(user != null) {
        		errorMessages.add("そのIDは既に使用されています");
        	}
        }
        if(StringUtils.isBlank(loginId)) {
        	errorMessages.add("ログインIDを入力してください");
        }else if (!loginId.matches("^[a-zA-Z0-9]{6,20}")) {
        	errorMessages.add("ログインIDは6文字以上20文字以下の半角英数字で入力してください");
        }
        if (loginId.contains(" ")) {
        	errorMessages.add("ログインIDは6文字以上20文字以下の半角英数字で入力してください");
        }
        if(password != "") {
        	if(!password.matches("^[!-~]{6,20}")) {
        		errorMessages.add("パスワードは6文字以上20文字以下の半角文字で入力してください");
        	}else if(loginId.contains(" ")) {
        		errorMessages.add("パスワードは6文字以上20文字以下の半角文字で入力してください");
        	}
        }
	    if (!password.equals(checkPass)) {
    		errorMessages.add("入力したパスワードと確認用パスワードが一致しません");
        }
        if(StringUtils.isBlank(name)) {
        	errorMessages.add("ユーザー名を入力してください");
        }
        if (name.length() > 10 ) {
        	errorMessages.add("ユーザー名は10文字以下で入力してください");
        }
	    if(branchId.equals("1")) {
	    	if(departmentId.equals("3"))  {
	    		errorMessages.add("支店と部署・役職の組み合わせが不正です");
	    	}else if(departmentId.equals("4")) {
	    		errorMessages.add("支店と部署・役職の組み合わせが不正です");
	    	}
	    }
	    if(!branchId.equals("1"))
	    	if(departmentId.equals("1") || departmentId.equals("2")) {
	    		errorMessages.add("支店と部署・役職の組み合わせが不正です");
	    	}
    	if (errorMessages.size() == 0) {
            return true;
    	}

    	else {
            return false;
        }
    }
}

src/moi_mahiro/controller/LoginServlet.java
package moi_mahiro.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import moi_mahiro.beans.User;
import moi_mahiro.service.LoginService;

@WebServlet(urlPatterns = { "/login" })
public class LoginServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        request.getRequestDispatcher("login.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

    	HttpSession session = request.getSession();
    	List<String> errorMessages = new ArrayList<String>();

    	if (isValid(request, errorMessages)) {

    		String login_id = request.getParameter("login_id");
    		String password = request.getParameter("password");

    		LoginService loginService = new LoginService();
    		User user = loginService.login(login_id, password);

    		session.setAttribute("loginUser", user);
    		response.sendRedirect("./");
        }else {
            session.setAttribute("errorMessages", errorMessages);

            String login_id = request.getParameter("login_id");

    		User user = new User();
    		user.setLoginId(login_id);

    		session.setAttribute("loginUser", user);

            request.getRequestDispatcher("/login.jsp").forward(request, response);
        }
    }
    private boolean isValid(HttpServletRequest request, List<String> errorMessages) {

    	 String login_id = request.getParameter("login_id");
         String password = request.getParameter("password");

         LoginService loginService = new LoginService();
         User user = loginService.login(login_id, password);

        if(login_id == "" || password == "") {
        	errorMessages.add("ログインIDまたはパスワードが入力されていません");
        }else if (user == null) {
        	errorMessages.add("ログインIDまたはパスワードが誤っています");
        }else if(user.getIsStopped().equals("1")) {
        	errorMessages.add("ログインIDまたはパスワードが誤っています");
        }
    	if (errorMessages.size() == 0) {
            return true;
    	}
    	else {
            return false;
    	}
    }

}

src/moi_mahiro/controller/NewMessageServlet.java
package moi_mahiro.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import moi_mahiro.beans.Message;
import moi_mahiro.beans.User;
import moi_mahiro.service.MessageService;
import moi_mahiro.service.UserService;

@WebServlet(urlPatterns = { "/NewMessage" })
public class NewMessageServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;


        @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

    	HttpSession session = request.getSession();
        User loginUser = (User) session.getAttribute("loginUser");
        User editUser = new UserService().getUser(loginUser.getLoginId());
        request.setAttribute("editUser", editUser);
        request.getRequestDispatcher("NewMessage.jsp").forward(request, response);

    }

    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        HttpSession session = request.getSession();

        List<String> errorMessages = new ArrayList<String>();

        if (isValid(request, errorMessages)) {

            User user = (User) session.getAttribute("loginUser");
            Message message = new Message();
            message.setText(request.getParameter("text"));
            message.setSubject(request.getParameter("subject"));
            message.setCategory(request.getParameter("category"));
            message.setUserId(user.getId());

            new MessageService().register(message);

            response.sendRedirect("./");
        } else {
            session.setAttribute("errorMessages", errorMessages);

            User user = (User) session.getAttribute("loginUser");
            Message message = new Message();
            message.setText(request.getParameter("text"));
            message.setSubject(request.getParameter("subject"));
            message.setCategory(request.getParameter("category"));
            message.setUserId(user.getId());

            request.setAttribute("message", message);

            request.getRequestDispatcher("NewMessage.jsp").forward(request, response);
        }
    }

    private boolean isValid(HttpServletRequest request, List<String> messages) {

        String subject = request.getParameter("subject");
        String text = request.getParameter("text");
        String category = request.getParameter("category");

        if (StringUtils.isBlank(category)) {
            messages.add("カテゴリーを入力してください");
        }
        if (10 < category.length()) {
            messages.add("カテゴリーは10文字以下で入力してください");
        }
        if (StringUtils.isBlank(subject)) {
            messages.add("件名を入力してください");
        }
        if (30 < subject.length()) {
            messages.add("件名は30文字以下で入力してください");
        }
        if (StringUtils.isBlank(text)) {
            messages.add("本文を入力してください");
        }
        if (1000 < text.length()) {
            messages.add("本文は1000文字以下で入力してください");
        }
        if (messages.size() == 0) {
            return true;
        } else {
            return false;
        }
    }

}

src/moi_mahiro/controller/UserManagementServlet.java
package moi_mahiro.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import moi_mahiro.beans.Management;
import moi_mahiro.service.ManagementService;

@WebServlet(urlPatterns = { "/UserManagement" })
public class UserManagementServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;


        @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        List<Management> managements = new ManagementService().getManagement();
        request.setAttribute("managements", managements);
        request.getRequestDispatcher("UserManagement.jsp").forward(request, response);

    }
}

WebContent/Edit.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>ユーザー編集</title>
    <link href="./css/style.css" rel="stylesheet" type="text/css">

    <script type="text/javascript">
		function check(){
			if(window.confirm('この内容で編集しますか？')){
			return true;
			}else{
				window.alert('編集がキャンセルされました');
				return false;
			}
		}

	</script>
    </head>
    <body>
		<div class =header>
			<a href="./">ホーム</a>
			<span  style="float: right;" >
				<span id="loginUser"><c:out value="${loginUser.name}　　"/></span>
			<a href="logout">ログアウト</a>
			</span>

		</div>
		<div class="title"><h2 align="center">ユーザー編集画面</h2></div>
		<div class=edit-main-contents>
			<c:if test="${ not empty errorMessages }">
			<div class="errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="message">
						<li><c:out value="${message}" />
					</c:forEach>
				</ul>
			</div>
			<c:remove var="errorMessages" scope="session"/>
			<input type="hidden" name="id" value="${management.id}">
		</c:if>
		<div class="editUser">
			<form action="edit" method="post" onSubmit="return check()">
			<table id= "editTable">
					<input type="hidden" name="id" value="${users.id}">
					<input type="hidden" name="login_id" value="${users.loginId}">
					<input type="hidden" name ="loginUserId" value="${loginUser.id}">
					<input name="loginPassword" type="hidden" id="loginPassword" value ="${loginUser.password}"/>

				<tr>
					<th>ログインID</th>
					<th id="input"><input type ="text"name = loginId value = "${users.loginId}"/><a id="conditions">　(6文字以上20文字以下 半角英数字)</a></th>
				</tr>
				<tr>
					<th>パスワード</th>
					<th id="input"><input type ="password" name = password value = "${users.password}"/><a id="conditions">　(6文字以上20文字以下 半角文字)</a></th>
				</tr>

				<tr>
					<th>パスワード確認用</th>
					<th id="input"><input type ="password" name = checkPassword /></th>
				</tr>
				<tr>
					<th>ユーザー名</th>
					<th id="input"><input type ="text" name = name value = "${users.name}"/><a id="conditions">　(10文字以下)</a></th>
				</tr>
				<tr>
					<th>支店</th>
					<c:if test = "${users.loginId  != loginUser.loginId}">
					<th id="input">
						<select name="branch_id"  >
							<c:forEach items="${branches}" var="branch">
								<c:choose>
									<c:when test = "${branch.id  == users.branchId}">
										<option value="${branch.id}" selected>${branch.branchName}</option>
									</c:when>
									<c:otherwise>
										<option value="${branch.id}">${branch.branchName}</option>
									</c:otherwise>
								</c:choose>
							</c:forEach>
						</select>
					</th>
					</c:if>
					<c:if test = "${users.loginId  == loginUser.loginId}">
						<th id="input">
							<select name="branch_id"  >
							<c:forEach items="${branches}" var="branch">
								<c:choose>
									<c:when test = "${branch.id  == users.branchId}">
										<option value="${branch.id}" selected>${branch.branchName}</option>
									</c:when>
								</c:choose>
							</c:forEach>
							</select>
						</th>
					</c:if>
				</tr>
				<tr>
					<th>部署・役職</th>
					<c:if test = "${users.loginId  != loginUser.loginId}">
					<th id="input"><select name="department_id">
						<c:forEach items="${departments}" var="department">
							<c:choose>
								<c:when test = "${department.id  == users.departmentId}">
									<option value="${department.id}" selected>${department.departmentName}</option>
								</c:when>
								<c:otherwise>
									<option value="${department.id}">${department.departmentName}</option>
								</c:otherwise>
							</c:choose>
						</c:forEach>
					</select>
					</th>
					</c:if>
					<c:if test = "${users.loginId  == loginUser.loginId}">
						<th id="input"><select name="department_id">
							<c:forEach items="${departments}" var="department">
								<c:choose>
									<c:when test = "${department.id  == users.departmentId}">
										<option value="${department.id}" selected>${department.departmentName}</option>
									</c:when>
								</c:choose>
							</c:forEach>
							</select>
						</th>
					</c:if>
				</tr>
				</table>
				<div class="button">
					<input type="submit" value="登録" id="record" />
				</div>
			</form>
			<div class=return>
				<a href="./UserManagement" id="returnButton">戻る</a>
			</div>
    		</div>
    	</div>
    	<div class="copyright">Copyright(c)MahiroMoi</div>
    </body>
</html>

WebContent/login.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>ログイン</title>
	<link href="./css/style.css" rel="stylesheet" type="text/css">
	</head>
	<body>
	<h1>掲示板課題</h1>
	<h2 align="center">ログイン画面</h2>

	<div class="login-main-contents">
		<c:if test="${ not empty errorMessages }">
			<div class="errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="message">
						<li><c:out value="${message}" />
					</c:forEach>
				</ul>
			</div>
			<c:remove var="errorMessages" scope="session"/>
		</c:if>

		<form action="login" method="post">
			<table id="loginBox">
				<tr>
					<th><label for="login_id" >ログインID</label></th>
					<th><input name="login_id" id="login_id" value="${loginUser.loginId}"/> </th>
				</tr>
				<tr>
					<th><label for="password">パスワード</label></th>
					<th><input name="password" type="password" id="password"/> </th>
			</tr>
			</table>
			<div class = "button">
				<input type="submit" value="ログイン" id="loginButton"/>
			</div>
		</form>
		<div class="copyright"> Copyright(c)MahiroMoi</div>
	</div>
	</body>
</html>

WebContent/top.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<% String nowDate = (new java.text.SimpleDateFormat("yyyy/MM/dd HH:mm:SS").format(new java.util.Date())); %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
    	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>掲示板課題</title>
        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
		<script src="./js/commentAjax.js"></script>

        <script type="text/javascript">
			function checkMessage(){
				if(window.confirm('投稿を削除しますか？')){
				return true;
				}else{
					window.alert('投稿の削除がキャンセルされました');
					return false;
				}
			}
			function checkComment(){
				if(window.confirm('コメントを削除しますか？')){
				return true;
				}else{
					window.alert('コメントの削除がキャンセルされました');
					return false;
				}
			}
		</script>
		<link href="./css/style.css" rel="stylesheet" type="text/css">

    </head>
    <body>
		<div class =header>
			<a href="./">ホーム</a>
			<a href="NewMessage">新規投稿</a>
			<c:if test = "${loginUser.branchId == 1 }">
				<a href="UserManagement">ユーザー管理</a>
			</c:if>
				<span  style="float: right;" ><a href="logout">ログアウト</a></span>
		</div>
		<div class="main-contents">
			<div class="profile">
				<div class="loginName"><h4>ユーザー名: <c:out value="${loginUser.name}" /></h4></div>
			</div>
			<form action="./" method="get">
				<div class="sort" >
					<label for="category" >カテゴリー：</label>
						<input type ="text" name = category  value="${category}" id="categoryLabel"/><br />
					<label for="start_at" >期間指定　：</label>
						<input type="date" min="2019-01-01" max="2099-12-31" name="start_at" value="${start_at}"  />
					<label for="end_at">～</label>
						<input type="date" min="2019-01-01" max="2099-12-31" name="end_at" value="${end_at}"/>
					<div class="button">
						<input type="submit" value="検索">
					</div>
				</div>
			</form>
			<div class="errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="message">
						<li><c:out value="${message}" /></li>
					</c:forEach>

				</ul>
			</div>
			<c:remove var="errorMessages" scope="session"/>
			<div class="messageArea">
				<c:forEach items="${messages}" var="message">
					<c:if test= "${message.id != 0}">
						<div class="messages">
							<div class="message" >
								<div class="category">カテゴリー：<c:out value="${message.category}" /></div>
								<div class="subject">件名:<c:out value="${message.subject}" /></div><br/>
								<div class="messageText">本文：<br/><c:out value="${message.text}" /></div><br/>
								<div class="createdDate">登録日時：<c:out value="${message.createdDate}" /></div>
								<div class="messageId">Id：<c:out value="${message.id}" /></div>
								<div class="name">登録者：<c:out value="${message.name}" /></div>
								<input type="hidden" id="messageNo" name="messageNo" value="${message.id}">
								<c:if test = "${loginUser.id == message.userId }">
								<form action="deleteMessage" method="post" onSubmit="return checkMessage()">
									<input type="hidden" name="messageId" value="${message.id}">
									<div class="deleteButton"><input type="submit" value="投稿削除">
									</div>
								</form>
							</c:if>
							</div>
							<div  class="comments">
								<c:forEach items="${comments}" var="comment">
									<c:if test="${message.id == comment.messageId}">
										<div class="comment" id="${message.id}">
											<div class="name">@<c:out value="${comment.name}" /></div>
											<div class="text"><c:out value="${comment.text}" /></div>
											<div class="createdDate"><c:out value="${comment.createdDate}" /></div>
											<c:if test = "${loginUser.id == comment.userId }">
												<form action="deleteComment" method="post" onSubmit="return checkComment()">
													<input type="hidden" name="commentId" value="${comment.id}">
													<div class="deleteButton">
													<input type="submit" value="コメント削除">
													</div>
												</form>
											</c:if>
										</div>
									</c:if>
								</c:forEach>
							</div>
							<div id="ajacComment_${message.id}"></div>

							<div class="form-area">
								<form id="comment-form">
									<textarea name="comment" cols="110" rows="2" wrap="soft" class="comment-box" id="text"></textarea><br />
									<input type="hidden" name="messageId" id="messageId" value="${message.id}">
									<input type="hidden" name="uerId"  id="userId" value="${loginUser.id}">
									<input type="hidden" name="userName"  id="userName" value="${loginUser.name}">
									 <button type="button" id="commentBottun">コメントする</button>
     				 			</form>
							</div>
						</div>
					</c:if>
				</c:forEach>
			</div>
			<div class="copyright"> Copyright(c)MahiroMoi></div>
		</div>
	</body>

</html>